name: "Issue Generation"
description: "Automation to keep track of what issues to generate for pull requests."
author: "jromero"
branding:
  icon: "check-square"
  color: "blue"
inputs:
  github-token:
    description: GitHub token of bot account.
    required: true
  bot-username:
    description: Username of bot account.
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
